### PR TITLE
Help text and image size

### PR DESCRIPTION
**Pull request by breyell**
Adds help text to make image selection and processing more transparent. Also adds support for another iOS image size.

### CODE REVIEW

**Review by stuartromanek — CHANGES_REQUESTED** [review]
Since we're here, why not just trim the min size down to something closer to the new use cases? Like 200x200 ?
I think the 500x500 size is a legacy thing

**Review by abea — COMMENTED** [review]
Agreed. Let's reduce the min size.

**Comment by breyell** [comment]
Agreed! Reduced to 200x200.

**Review by stuartromanek — APPROVED** [review]

**Comment by abea** [comment]
Remember those Changelog updates, folks.

**Pull request merged**
